const Request$2 = {
  formData: [AsyncFunction (anonymous)],
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    method: 'GET',
    localURLsOnly: false,
    unsafeRequest: false,
    body: null,
    client: {},
    reservedClient: null,
    replacesClientId: '',
    window: 'client',
    keepalive: false,
    serviceWorkers: 'all',
    initiator: '',
    destination: '',
    priority: null,
    origin: 'client',
    policyContainer: 'client',
    referrer: 'client',
    referrerPolicy: '',
    mode: 'cors',
    useCORSPreflightFlag: false,
    credentials: 'same-origin',
    useCredentials: false,
    cache: 'default',
    redirect: 'follow',
    integrity: '',
    cryptoGraphicsNonceMetadata: '',
    parserMetadata: '',
    reloadNavigation: false,
    historyNavigation: false,
    userActivation: false,
    taintedOrigin: false,
    redirectCount: 0,
    responseTainting: 'basic',
    preventNoCacheCacheControlHeaderModification: false,
    done: false,
    timingAllowFailed: false,
    headersList: HeadersList$2 {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    url: URL {
      href: 'http://rag.loc/contact?message_name=Mary&message_text=Lorem+ipsum+dolor+sit+amet.',
      origin: 'http://rag.loc',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'rag.loc',
      hostname: 'rag.loc',
      port: '',
      pathname: '/contact',
      search: '?message_name=Mary&message_text=Lorem+ipsum+dolor+sit+amet.',
      searchParams: URLSearchParams { 'message_name' => 'Mary', 'message_text' => 'Lorem ipsum dolor sit amet.' },
      hash: ''
    }
  },
  [Symbol(signal)]: AbortSignal { aborted: false },
  [Symbol(headers)]: HeadersList$2 {
    [Symbol(headers map)]: Map(15) {
      'host' => 'rag.loc',
      'x-real-ip' => '172.16.238.1',
      'x-forwarded-for' => '172.16.238.1',
      'connection' => 'upgrade',
      'user-agent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0',
      'accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
      'accept-language' => 'en,de;q=0.7,en-US;q=0.3',
      'accept-encoding' => 'gzip, deflate, br',
      'dnt' => '1',
      'upgrade-insecure-requests' => '1',
      'sec-fetch-dest' => 'document',
      'sec-fetch-mode' => 'navigate',
      'sec-fetch-site' => 'same-origin',
      'sec-gpc' => '1',
      'if-none-match' => '"1o3e5py"'
    },
    [Symbol(headers map sorted)]: null
  }
}
const Request$2 = {
  formData: [AsyncFunction (anonymous)],
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    method: 'GET',
    localURLsOnly: false,
    unsafeRequest: false,
    body: null,
    client: {},
    reservedClient: null,
    replacesClientId: '',
    window: 'client',
    keepalive: false,
    serviceWorkers: 'all',
    initiator: '',
    destination: '',
    priority: null,
    origin: 'client',
    policyContainer: 'client',
    referrer: 'client',
    referrerPolicy: '',
    mode: 'cors',
    useCORSPreflightFlag: false,
    credentials: 'same-origin',
    useCredentials: false,
    cache: 'default',
    redirect: 'follow',
    integrity: '',
    cryptoGraphicsNonceMetadata: '',
    parserMetadata: '',
    reloadNavigation: false,
    historyNavigation: false,
    userActivation: false,
    taintedOrigin: false,
    redirectCount: 0,
    responseTainting: 'basic',
    preventNoCacheCacheControlHeaderModification: false,
    done: false,
    timingAllowFailed: false,
    headersList: HeadersList$2 {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [ [URL] ],
    url: URL {
      href: 'http://rag.loc/contact?message_name=Mary&message_text=Lorem+ipsum+dolor+sit+amet.',
      origin: 'http://rag.loc',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'rag.loc',
      hostname: 'rag.loc',
      port: '',
      pathname: '/contact',
      search: '?message_name=Mary&message_text=Lorem+ipsum+dolor+sit+amet.',
      searchParams: URLSearchParams { 'message_name' => 'Mary', 'message_text' => 'Lorem ipsum dolor sit amet.' },
      hash: ''
    }
  },
  [Symbol(signal)]: AbortSignal { aborted: false },
  [Symbol(headers)]: HeadersList$2 {
    [Symbol(headers map)]: Map(17) {
      'host' => 'rag.loc',
      'x-real-ip' => '172.16.238.1',
      'x-forwarded-for' => '172.16.238.1',
      'connection' => 'upgrade',
      'user-agent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0',
      'accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
      'accept-language' => 'en,de;q=0.7,en-US;q=0.3',
      'accept-encoding' => 'gzip, deflate, br',
      'dnt' => '1',
      'referer' => 'https://rag.loc/contact?message_name=Mary&message_text=Lorem+ipsum+dolor+sit+amet.',
      'upgrade-insecure-requests' => '1',
      'sec-fetch-dest' => 'document',
      'sec-fetch-mode' => 'navigate',
      'sec-fetch-site' => 'same-origin',
      'sec-fetch-user' => '?1',
      'sec-gpc' => '1',
      'if-none-match' => '"1o3e5py"'
    },
    [Symbol(headers map sorted)]: null
  }
}
